INSERT INTO `Categoria` (`categoria`, `descripcion`) VALUES ('java', 'libros java')
INSERT INTO `Categoria` (`categoria`, `descripcion`) VALUES ('web', 'libros web')
INSERT INTO `Categoria` (`categoria`, `descripcion`) VALUES ('programacion', 'libros de programacion')
INSERT INTO `Libros` (`isbn`, `titulo`, `autor`,  `precio`, `categoria`) VALUES ('1AB', 'Java', 'cecilio', 10, 'java')
INSERT INTO `Libros` (`isbn`, `titulo`, `autor`,  `precio`, `categoria`) VALUES ('2AC', 'Java Web', 'cecilio', 15, 'java')
INSERT INTO `Libros` (`isbn`, `titulo`, `autor`,  `precio`, `categoria`) VALUES ('3BC', 'html', 'gema', 8, 'web')
INSERT INTO `Libros` (`isbn`, `titulo`, `autor`,  `precio`, `categoria`) VALUES ('4BD', 'html5', 'andres', 7, 'web')
INSERT INTO `Libros` (`isbn`, `titulo`, `autor`,  `precio`, `categoria`) VALUES ('5EF', 'python', 'paco', 15, 'programacion')